import Link from "next/link";
import { Inter } from "next/font/google";
// Components
import SearchBar from "./SearchBar";
// React Icons
import { LuInbox } from "react-icons/lu";
import { RiChat3Line } from "react-icons/ri";
import "./globals.css";
import ProfileImage from "@/components/ProfileImage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-white h-14 flex items-center justify-between px-5 fixed top-0 w-full shadow-sm">
          <Link href={"/"}>Home</Link>
          <SearchBar />
          <div className="flex items-center gap-4">
            <LuInbox size={25} className="hover:cursor-pointer" />
            <Link href={"/message"}>
              <RiChat3Line size={25} className="hover:cursor-pointer" />
            </Link>
            <ProfileImage />
          </div>
        </nav>
        <div className="pt-14 h-full overflow-y-scroll">
          {children}
        </div>
      </body>
    </html>
  );
}
